import {
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowUpFromLine,
  Ban,
  Beer,
  Binoculars,
  BookOpen,
  Brain,
  Building2,
  Circle,
  Clock,
  Clover,
  CloudFog,
  Coins,
  Crosshair,
  Crown,
  DoorOpen,
  Droplets,
  Dumbbell,
  Eye,
  EyeOff,
  Fan,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Footprints,
  Gem,
  Hand,
  HandCoins,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hexagon,
  Hourglass,
  KeyRound,
  type LucideIcon,
  Layers,
  Leaf,
  Lock,
  Megaphone,
  MessageCircle,
  PersonStanding,
  Rotate3d,
  ScrollText,
  Shield,
  ShieldOff,
  ShoppingBasket,
  Siren,
  Skull,
  Sofa,
  Sparkles,
  Star,
  Sword,
  Swords,
  Target,
  Tent,
  ThumbsDown,
  Wand,
  Wind,
  Zap,
} from "lucide-react"

// Maps the semantic icon names used in content files to real Lucide icons.
// Minigame cards, achievements, and UI all resolve through this map.
const ICONS: Record<string, LucideIcon> = {
  // Achievements
  swords: Swords,
  "shield-off": ShieldOff,
  shield: Shield,
  wind: Wind,
  coins: Coins,
  star: Star,
  crown: Crown,
  dumbbell: Dumbbell,
  "message-circle": MessageCircle,
  sparkles: Sparkles,
  "heart-pulse": HeartPulse,
  "heart-handshake": HeartHandshake,
  hourglass: Hourglass,
  tent: Tent,
  flame: Flame,
  flag: Flag,
  skull: Skull,
  gem: Gem,
  clover: Clover,
  hand: Hand,
  brain: Brain,
  // Minigame duel icons
  sword: Sword,
  fist: Hand,
  chair: Sofa,
  "rotate-3d": Rotate3d,
  ban: Ban,
  zap: Zap,
  hexagon: Hexagon,
  wand: Wand,
  footprints: Footprints,
  siren: Siren,
  "cloud-fog": CloudFog,
  "arrow-down": ArrowDown,
  horse: Sword,
  // Minigame activity icons
  lock: Lock,
  "eye-off": EyeOff,
  "arrow-up-from-line": ArrowUpFromLine,
  "hand-coins": HandCoins,
  beer: Beer,
  "flask-conical": FlaskConical,
  "thumbs-down": ThumbsDown,
  "shopping-basket": ShoppingBasket,
  "building-2": Building2,
  megaphone: Megaphone,
  crosshair: Crosshair,
  eye: Eye,
  layers: Layers,
  leaf: Leaf,
  fish: Fish,
  binoculars: Binoculars,
  "scroll-text": ScrollText,
  "key-round": KeyRound,
  handshake: Handshake,
  fan: Fan,
  droplets: Droplets,
  target: Target,
  "person-running": PersonStanding,
  "arrow-up": ArrowUp,
  "arrow-right": ArrowRight,
  "book-open": BookOpen,
  circle: Circle,
  clock: Clock,
  "door-open": DoorOpen,
  heart: Heart,
}

export function AchIcon({ name, size = 18 }: { name: string; size?: number }) {
  const Icon = ICONS[name] ?? Sparkles
  return <Icon size={size} strokeWidth={1.75} aria-hidden="true" />
}
